using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProjectAdventure
{
    class UserDetails
    {
        /*declaring a new class <UserDetails> so as to call our json output data. 
        classes are usually automatically generated by the ado.net framework.*/

        public string Name { get; set; }
        public string Email { get; set; }

        public UserDetails(string name, string email)
        {
            Name = name;
            Email = email;
        }
    }
}
